Add readme
brytannia/sloboda-edu-dashboard pull request #60
Opened 2016-10-16 07:16 UTC by k1r8r0wn

Closed issue #57

2016-10-18 08:37 UTC, rakvium requested changes

2016-10-18 08:37 UTC, rakvium commented on Gemfile
> +gem 'paperclip'
@k1r8r0wn why do you add a gem in the pull request about readme adding? :confused:

2016-10-18 09:01 UTC, rakvium requested changes

2016-10-18 09:01 UTC, rakvium commented on README.md
> +5. Rename existing `database.yml.sample` to `database.yml` (it stores the db configs);
It's better to copy rather than rename, to not affect the git:
`cp config/database.yml.sample config/database.yml`

2016-10-18 09:04 UTC, k1r8r0wn commented on Gemfile
> +gem 'paperclip'
By mistake, already fix that.

2016-10-22 11:29 UTC, brytannia approved these changes

2016-10-22 11:31 UTC, merged